server:
  port: 8061

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-server-mobile
zuul:
  routes:
    employee-service:
      path: /employee-service/**
      url: http://localhost:8095/employee-service/
    organization-service:
      path: /organization-service/**
      url: http://localhost:8096/organization-service/
    department-service:
      path: /department-service/**
      url: http://localhost:8097/department-service/